import {LIBRARY_URL,LIBRARY_VERSION,CANDIDATES,PROMPTS,modelCatalog,captureEnvironment,finishMeasurement,summary,now} from './ai-bench-metrics.mjs';
const $=id=>document.getElementById(id);
let webllm=null,engine=null,worker=null,loadedModel=null,loadedPath=null,busy=false,stopRequested=false,report=null,environment=null,catalog=[];
const fmt=x=>x==null?'unavailable':Number(x).toFixed(2);
function status(t){$('status').textContent=t;}
function log(t){$('progress').textContent+=t+'\n';$('progress').scrollTop=$('progress').scrollHeight;}
function err(e){return String(e?.stack||e);}
function settings(){const repeats=Number($('repeats').value),maxTokens=Number($('maxTokens').value);if(!Number.isInteger(repeats)||repeats<1||repeats>5)throw Error('Repeats must be 1–5');if(!Number.isInteger(maxTokens)||maxTokens<16||maxTokens>160)throw Error('Output token limit must be 16–160');return {model:$('model').value,path:$('path').value,profiles:$('profile').value.split(','),repeats,maxTokens,temperature:0,seed:42,libraryVersion:LIBRARY_VERSION};}
function refresh(){const blocked=busy||!webllm;$('load').disabled=blocked;$('model').disabled=blocked;$('path').disabled=blocked;$('run').disabled=busy||!engine;$('stop').disabled=!busy;$('share').disabled=!report;$('save').disabled=!report;$('copy').disabled=!report;}
function update(){if(!report)return;report.summary=summary(report.runs);$('report').textContent=JSON.stringify({status:report.status,model:report.config?.model,summary:report.summary,errors:report.errors},null,2);
const rows=report.runs.map(r=>`<tr><td>${r.profile} #${r.repeat}</td><td>${r.status}</td><td>${r.metrics?fmt(r.metrics.timeToFirstVisibleTextMs):'–'}</td><td>${r.metrics?fmt(r.metrics.usage.modelDecodeTokensPerSecond??r.metrics.approximateDecodeTokensPerSecond):'–'}</td><td>${r.metrics?fmt(r.metrics.endToEndTokensPerSecond):'–'}</td></tr>`).join('');
$('results').innerHTML='<div class="small muted">Timing in milliseconds; rates in model tokens/s when usage exists. Derived decode rate is approximate and explicitly marked in JSON.</div><table><thead><tr><th>Profile</th><th>Status</th><th>First text ms</th><th>Decode tok/s*</th><th>End-end tok/s</th></tr></thead><tbody>'+rows+'</tbody></table>';refresh();
try{localStorage.setItem('pocketbench-ai-latest',JSON.stringify(report));}catch(e){log('Local persistence unavailable: '+String(e));}}
async function closeEngine(){if(engine){try{await engine.unload?.();}catch(e){log('Unload notice: '+String(e));}engine=null;}if(worker){worker.terminate();worker=null;}loadedModel=null;loadedPath=null;}
async function loadModel(){if(busy)return;busy=true;refresh();const c=settings();const m=catalog.find(x=>x.id===c.model);if(!m?.available){busy=false;refresh();throw Error('Model absent from pinned runtime catalog');}
try{await closeEngine();status(`Loading ${c.model}; large first-time download may take substantial time…`);log(`Model=${c.model}; path=${c.path}; catalog estimated GPU memory=${m.estimatedRuntimeMemoryMB??'unknown'} MB (NOT download size or observed allocation).`);
const options={initProgressCallback:p=>{status('Model load: '+(p.text||JSON.stringify(p)));}};
const t=now();
if(c.path==='worker'){worker=new Worker('./ai-bench-worker.mjs',{type:'module'});engine=await webllm.CreateWebWorkerMLCEngine(worker,c.model,options);}
else engine=await webllm.CreateMLCEngine(c.model,options);
loadedModel=c.model;loadedPath=c.path;const loadMs=now()-t;
report={app:'PocketBench client LLM inference',version:'0.1.0',status:'model-ready',startedAt:new Date().toISOString(),endedAt:null,environment,config:c,modelRecord:m,load:{wallMs:loadMs,firstOrCached:'unknown (browser cache state not measured)',runtimeURL:LIBRARY_URL},runs:[],errors:[],methodology:{tokenCounts:'Only model-reported usage counts as tokens. Stream chunks and characters are never tokens.',ttft:'Elapsed from call before create() to first nonempty streamed text; includes browser overhead and prefill.',decode:'Prefer usage.extra.decode_tokens_per_s; otherwise (completion_tokens−1)/(last−first visible) approximates decode.',prompt:'Synthetic fixed prompts. Each request passes system + one user message; engine is reused, potential internal prefix cache is not isolated.',network:'Inference is local; runtime and model weights are fetched from external CDNs on initial load.',memory:'Catalog vram_required_MB is an estimate, not measured RAM or model download size.',confidence:'No independent token accuracy/perplexity benchmark. No actual GPU allocation, NPU use, battery power or thermal sensors.'}};
update();log(`Model ready after ${Math.round(loadMs)} ms.`);status('Model ready. Tap Run benchmark; optional long prompt may take longer.');
}catch(e){status('Model loading FAILED: '+err(e));log(err(e));if(!report||report.config?.model!==c.model)report={app:'PocketBench client LLM inference',version:'0.1.0',status:'load-failed',environment,config:c,modelRecord:m,runs:[],errors:[],endedAt:new Date().toISOString()};report.errors.push({stage:'load',error:err(e)});report.status='load-failed';update();await closeEngine();}
finally{busy=false;refresh();}}
async function infer(profile,repeat,c){const prompt=PROMPTS[profile];const start=now();let firstVisible=null,output='',chunkCount=0,usage=null;try{
const stream=await engine.chat.completions.create({messages:[{role:'system',content:'You are a concise assistant. Respond directly without exposing private reasoning.'},{role:'user',content:prompt}],temperature:c.temperature,seed:c.seed,max_tokens:c.maxTokens,stream:true,stream_options:{include_usage:true}});
for await(const chunk of stream){const text=chunk.choices?.[0]?.delta?.content||'';if(text){if(firstVisible===null)firstVisible=now();output+=text;chunkCount++;}if(chunk.usage)usage=chunk.usage;}
const metrics=finishMeasurement({start,firstVisible,end:now(),chunkCount,usage,text:output});return {profile,repeat,status:'completed',promptCharacters:prompt.length,metrics};
}catch(e){return {profile,repeat,status:'failed',promptCharacters:prompt.length,elapsedBeforeErrorMs:now()-start,error:err(e)};}}
async function runSuite(){if(busy||!engine)return;let c;try{c=settings();}catch(e){status(err(e));return;}if(c.model!==loadedModel||c.path!==loadedPath){status('Model or execution path changed. Load selected model first.');return;}
busy=true;stopRequested=false;refresh();report.status='running';report.endedAt=null;report.config=c;report.runs=[];report.errors=[];report.benchmarkStartAt=new Date().toISOString();update();
try{status('Warmup: short synthetic prompt, 16 max tokens…');const warmStart=now();let warmupError=null;
try{const stream=await engine.chat.completions.create({messages:[{role:'user',content:'Write ten simple nouns.'}],max_tokens:16,temperature:0,seed:42,stream:true});for await(const _ of stream){};}catch(e){warmupError=err(e);log('Warmup failed: '+warmupError);}
report.warmup={elapsedMs:now()-warmStart,error:warmupError};if(warmupError)throw Error('Warmup failed; do not interpret later output.');
for(const profile of c.profiles){for(let repeat=1;repeat<=c.repeats;repeat++){if(stopRequested)break;status(`Running ${profile} ${repeat}/${c.repeats}…`);const r=await infer(profile,repeat,c);report.runs.push(r);log(`${profile} #${repeat}: ${r.status}, TTFT=${fmt(r.metrics?.timeToFirstVisibleTextMs)}ms, model decode=${fmt(r.metrics?.usage.modelDecodeTokensPerSecond)} tok/s, E2E=${fmt(r.metrics?.endToEndTokensPerSecond)} tok/s`);if(r.status==='failed')report.errors.push({stage:'inference',profile,repeat,error:r.error});update();}if(stopRequested)break;}
report.status=stopRequested?'partial':report.errors.length?'completed-with-errors':'completed';status('Benchmark '+report.status+'. Save / share the JSON.');
}catch(e){report.errors.push({stage:'suite',error:err(e)});report.status='failed';status('Benchmark FAILED: '+err(e));}
finally{report.endedAt=new Date().toISOString();busy=false;update();refresh();}}
function json(){return JSON.stringify(report,null,2);}
function filename(){return 'pocketbench-ai-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';}
function download(){if(!report)return;const url=URL.createObjectURL(new Blob([json()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename();a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('load').onclick=()=>{loadModel().catch(e=>{status(err(e));busy=false;refresh();});};$('run').onclick=()=>runSuite();$('stop').onclick=()=>{stopRequested=true;status('Stop requested: current inference will finish before stopping.');};$('save').onclick=download;
$('share').onclick=async()=>{if(!report)return;try{const file=new File([json()],filename(),{type:'application/json'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'PocketBench mobile AI result'});else download();}catch(e){if(e.name!=='AbortError')status('Share unavailable: '+String(e)+'; use Save JSON.');}};
$('copy').onclick=async()=>{if(!report)return;const txt=JSON.stringify({model:report.config?.model,status:report.status,summary:report.summary},null,2);try{await navigator.clipboard.writeText(txt);status('Summary copied.');}catch(e){status('Clipboard unavailable: '+String(e));}};
$('model').onchange=()=>{if(engine&&$('model').value!==loadedModel){status('Model changed. Select Load selected model before running.');$('run').disabled=true;}};$('path').onchange=()=>{if(engine&&$('path').value!==loadedPath){status('Path changed. Load selected model before running.');$('run').disabled=true;}};
(async()=>{try{environment=await captureEnvironment();$('environment').textContent=`WebGPU: ${environment.webgpu?'yes':'no'}; WebNN: ${environment.webnn?'exposed':'not exposed'}; worker supported: ${typeof Worker!=='undefined'?'yes':'no'}; GPU features: ${environment.adapter?.features?.join(', ')||'unavailable'}; maxBufferSize: ${environment.adapter?.limits?.maxBufferSize??'unknown'}.`;
if(!environment.webgpu)throw Error('This WebLLM experiment needs WebGPU. Use a different browser/backend experiment for WASM.');status('Importing pinned WebLLM 0.2.85 runtime (no model weights yet)…');webllm=await import(LIBRARY_URL);catalog=modelCatalog(webllm.prebuiltAppConfig.model_list);
const available=catalog.filter(m=>m.available);if(!available.length)throw Error('No benchmark candidate found in pinned runtime catalog');$('model').replaceChildren(...available.map(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=`${m.id} · estimated runtime GPU memory ${m.estimatedRuntimeMemoryMB??'?'} MB`;return o;}));$('model').value=available.some(x=>x.id===CANDIDATES[1].id)?CANDIDATES[1].id:available[0].id;
$('catalog').textContent=`Pinned WebLLM ${LIBRARY_VERSION}; ${available.length}/${CANDIDATES.length} candidate models found in actual catalog. These are candidates, not speed measurements. No weights loaded.`;status('Runtime ready. Choose model and tap Load selected model to download weights.');refresh();
const previous=localStorage.getItem('pocketbench-ai-latest');if(previous){const b=document.createElement('button');b.className='secondary';b.textContent='Restore previous saved report';b.onclick=()=>{try{report=JSON.parse(previous);update();status('Previous local report restored; it is NOT a new run.');}catch(e){status('Previous report unreadable: '+String(e));}};$('results').after(b);}
}catch(e){status('Initialization FAILED: '+err(e));log(err(e));refresh();}})();
