import {STORAGE_KEY,PROBES,chatOptions,wasInterrupted,validateChoice,summarize,snapshot,recover} from './ai-context-core.mjs';
import {oneInference} from './ai-diagnose-core.mjs';
import {LIBRARY_URL,LIBRARY_VERSION} from './ai-bench-metrics.mjs';
const $=id=>document.getElementById(id);
const MODEL_IDS=['SmolLM2-135M-Instruct-q0f16-MLC','SmolLM2-360M-Instruct-q4f16_1-MLC','Qwen3-0.6B-q4f16_1-MLC'];
let runtime,engine=null,worker=null,loaded=null,busy=false,report=null,models=[];
const stringError=e=>String(e?.stack||e);
function status(s){$('status').textContent=s;}
function persist(){try{snapshot(localStorage,report);}catch(e){$('previous').textContent='Checkpoint storage failed: '+stringError(e);}}
function mark(stage,extra={}){if(!report)return;report.stage=stage;report.events.push({at:new Date().toISOString(),stage,...extra});if(report.events.length>100)report.events.shift();persist();paint();}
function paint(){if(!report)return;$('events').textContent=report.events.slice(-16).map(e=>`${e.at.slice(11,19)} ${e.stage}${e.error?' — '+e.error:''}`).join('\n');$('results').textContent=JSON.stringify({phase:report.phase,config:report.config,load:report.load,results:report.results.map(r=>({probe:r.id,...summarize(r)})),errors:report.errors},null,2);}
function controls(){const ready=!!runtime&&!busy;$('model').disabled=!ready;$('path').disabled=busy;$('context').disabled=busy;$('load').disabled=!ready;$('run').disabled=busy||!engine;$('ladder').disabled=busy||!engine;$('release').disabled=busy||(!engine&&!worker);}
function fresh(){return {app:'PocketBench AI Context Isolation',version:'2.0.0',runtime:LIBRARY_VERSION,pageUrl:location.href,startedAt:new Date().toISOString(),finishedAt:null,phase:'ready',stage:'ready',config:null,environment:null,modelRecord:null,load:null,events:[],results:[],errors:[],methodology:{runtime:'Pinned WebLLM 0.2.85, same model weights and compiled model library across context options.',context:'Optional chatOpts.context_window_size passed at model load; not actual measured GPU memory or guaranteed reduction.',usage:'Reported token usage is preserved; a nonempty response with zero reported completion tokens is flagged, not recomputed from characters.',scope:'One model/configuration per report; no implicit repeats, no automatic model download or crash retry.',limits:'Browser diagnostics cannot establish iOS process kill reason, actual RAM, physical NPU access, or thermal sustainability.'}};}
const previous=recover(localStorage);if(previous){report=previous;$('previous').textContent=wasInterrupted(previous)?`Unfinished prior run: ${previous.phase} / ${previous.stage}. Export this checkpoint BEFORE loading a different configuration. This does not identify the crash cause.`:`Saved run: ${previous.phase} / ${previous.stage}. Export it before loading a new configuration.`;paint();}else $('previous').textContent='No saved checkpoint. An inference attempt will preserve its most recent stage.';
window.addEventListener('error',e=>{if(report){report.errors.push({stage:'window-error',error:e.message});mark('window-error',{error:e.message});}});
window.addEventListener('unhandledrejection',e=>{if(report){report.errors.push({stage:'unhandled-rejection',error:stringError(e.reason)});mark('unhandled-rejection',{error:stringError(e.reason)});}});
window.addEventListener('pagehide',()=>{if(report){report.events.push({at:new Date().toISOString(),stage:'pagehide',precedingStage:report.stage,note:'Can occur during ordinary navigation or OS lifecycle.'});persist();}});
function output(){return JSON.stringify(report,null,2);}
function filename(){return 'pocketbench-ai-context-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';}
function download(){if(!report)return;const url=URL.createObjectURL(new Blob([output()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename();a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('save').onclick=download;
$('share').onclick=async()=>{if(!report)return;try{const file=new File([output()],filename(),{type:'application/json'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'PocketBench AI context result'});else download();}catch(e){if(e?.name!=='AbortError')status('Share failed: '+stringError(e)+'; use Save JSON.');}};
$('clear').onclick=()=>{if(busy)return;try{localStorage.removeItem(STORAGE_KEY);}catch{}report=null;$('events').textContent='';$('results').textContent='';$('previous').textContent='Checkpoint cleared; model cache is unchanged.';status('Ready.');};
async function release(){if(worker){worker.terminate();worker=null;engine=null;}else if(engine){const old=engine;engine=null;try{await old.unload?.();}catch(e){mark('unload-error',{error:stringError(e)});}}loaded=null;controls();}
$('release').onclick=async()=>{if(busy)return;busy=true;controls();mark('manual-release');try{await release();status('Model released.');}finally{busy=false;controls();}};
async function load(){if(busy||!runtime)return;const selected=validateChoice({model:$('model').value,path:$('path').value,context:Number($('context').value)},models);const meta=models.find(m=>m.model_id===selected.model);busy=true;controls();try{await release();report=fresh();report.phase='loading';report.config=selected;report.modelRecord={modelId:meta.model_id,modelURL:meta.model,modelLib:meta.model_lib,requiredFeatures:meta.required_features??[],catalogEstimatedRuntimeMemoryMB:meta.vram_required_MB??null,defaultOverrides:meta.overrides??null};report.environment={userAgent:navigator.userAgent,visibility:document.visibilityState,webgpu:!!navigator.gpu,crossOriginIsolated:globalThis.crossOriginIsolated??null};mark('load-before-await',{...selected});status('Loading selected model. Weights only download after this action.');
const t=performance.now();const options={initProgressCallback:p=>{if(p.text&&(/finish|cache|download|compile|loading/i.test(p.text)))mark('load-progress',{text:p.text.slice(0,160)});}};
const chatOpts=chatOptions(selected.context);if(selected.path==='worker'){worker=new Worker('./ai-bench-worker.mjs',{type:'module'});worker.addEventListener('error',e=>{if(report){report.errors.push({stage:'worker-error',error:e.message});mark('worker-error',{error:e.message});}});worker.addEventListener('messageerror',()=>mark('worker-messageerror'));mark('worker-engine-await');engine=await runtime.CreateWebWorkerMLCEngine(worker,selected.model,options,chatOpts);}else{mark('main-engine-await');engine=await runtime.CreateMLCEngine(selected.model,options,chatOpts);}
report.load={wallMs:performance.now()-t,cacheState:'unknown',contextOverride:chatOpts??null};loaded=selected;report.phase='ready';mark('model-ready');status('Model loaded. Run ONE minimal inference probe.');$('previous').textContent='Current report is saved after each stage; export before loading another model.';
}catch(e){const msg=stringError(e);if(report){report.errors.push({stage:'load',error:msg});report.phase='failed';report.finishedAt=new Date().toISOString();mark('load-failed',{error:msg});}status('Load failed: '+msg);await release();}finally{busy=false;controls();}}
$('load').onclick=()=>load().catch(e=>status('Load handler failed: '+stringError(e)));
async function run(probes){if(busy||!engine||!loaded)return;const choice={model:$('model').value,path:$('path').value,context:Number($('context').value)};if(JSON.stringify(choice)!==JSON.stringify(loaded)){status('Model, execution path or context changed. Load configuration before inference.');return;}busy=true;controls();report.phase='inference';report.finishedAt=null;mark('inference-start',{probes:probes.map(p=>p.id)});try{for(const p of probes){mark('probe-before-await',{probe:p.id,tokens:p.tokens,stream:p.stream});status(`Running ${p.tokens}-token ${p.stream?'stream':'nonstream'} probe…`);const r=await oneInference(engine,p,{mark:(stage,extra)=>mark(stage,{probe:p.id,...extra})});r.summary=summarize(r);report.results.push(r);mark('probe-completed',{probe:p.id,...r.summary});if(r.summary.tokenUsageDiscrepancy)mark('usage-discrepancy',{probe:p.id,note:'Nonempty output but completion_tokens=0; not a measured zero-token output.'});}report.phase='completed';report.finishedAt=new Date().toISOString();mark('all-probes-completed');status('Probe complete. Export the report before changing model or context.');}catch(e){const msg=stringError(e);report.errors.push({stage:'inference',error:msg});report.phase='failed';report.finishedAt=new Date().toISOString();mark('inference-failed',{error:msg});status('Inference failed: '+msg+'; export JSON.');}finally{busy=false;controls();}}
$('run').onclick=()=>run([PROBES.find(p=>p.id===$('probe').value)]);
$('ladder').onclick=()=>run(PROBES);
(async()=>{try{status('Probing WebGPU and importing pinned runtime (no weights)…');if(!navigator.gpu)throw Error('navigator.gpu unavailable');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('No adapter');const features=[...adapter.features];$('device').textContent=`Adapter vendor: ${adapter.info?.vendor??'unknown'}; shader-f16: ${features.includes('shader-f16')}; maxBufferSize: ${adapter.limits?.maxBufferSize??'unknown'} bytes.`;if(!report){report=fresh();report.phase='runtime-import';mark('runtime-import');}runtime=await import(LIBRARY_URL);models=runtime.prebuiltAppConfig.model_list.filter(m=>MODEL_IDS.includes(m.model_id)&&(m.required_features??[]).every(f=>features.includes(f))).sort((a,b)=>(a.vram_required_MB??Infinity)-(b.vram_required_MB??Infinity));if(!models.length)throw Error('No compatible catalog candidates');$('model').replaceChildren(...models.map(m=>{const o=document.createElement('option');o.value=m.model_id;o.textContent=`${m.model_id} · catalog estimate ${m.vram_required_MB??'?'} MB`;return o;}));if(report.phase==='runtime-import'){report.phase='ready';mark('runtime-ready');}status('Runtime ready. Start with the smallest model, or choose Qwen3 for controlled reproduction.');controls();}catch(e){const msg=stringError(e);status('Bootstrap failed: '+msg);if(report){report.errors.push({stage:'bootstrap',error:msg});report.phase='failed';report.finishedAt=new Date().toISOString();mark('bootstrap-failed',{error:msg});}controls();}})();
