import {APP_VERSION,WLLAMA_VERSION,RUNTIME_URL,WASM_URL,STORAGE_KEY,MODELS,validateChoice,resultMetrics,incomplete,saveCheckpoint} from './ai-wllama-core.mjs';
const $=id=>document.getElementById(id),clock=()=>performance.now();let WllamaClass=null,engine=null,loaded=null,busy=false,report=null;
const failText=e=>String(e?.stack||e?.message||e),time=()=>new Date().toISOString();
function persist(){try{saveCheckpoint(localStorage,report);}catch(e){$('previous').textContent='Checkpoint unavailable: '+failText(e);}}
function mark(stage,details={}){if(!report)return;report.stage=stage;report.events.push({at:time(),stage,...details});if(report.events.length>140)report.events.shift();persist();render();}
function render(){if(!report)return;$('events').textContent=report.events.slice(-16).map(e=>`${e.at.slice(11,19)} ${e.stage}${e.error?': '+e.error:''}`).join('\n');}
function status(s){$('status').textContent=s;}
function controls(){const ready=!!engine&&!busy;$('load').disabled=busy;$('release').disabled=busy||!engine;$('one').disabled=!ready;$('sixtyfour').disabled=!ready;for(const id of ['model','offload','context','files'])$(id).disabled=busy;}
function newReport(config){return {app:'PocketBench independent GGUF inference',version:APP_VERSION,runtime:{name:'wllama',version:WLLAMA_VERSION,module:RUNTIME_URL,wasm:WASM_URL},startedAt:time(),finishedAt:null,phase:'loading',stage:'load-start',config,environment:{userAgent:navigator.userAgent,webgpu:!!navigator.gpu,wasm:typeof WebAssembly!=='undefined',crossOriginIsolated:globalThis.crossOriginIsolated??null,hardwareConcurrency:navigator.hardwareConcurrency??null},events:[],load:null,results:[],errors:[],methodology:'Single-thread CPU Wasm n_gpu_layers=0; optional n_gpu_layers 4/999. GGUF not same bytes/quant as WebLLM artifacts. Token rates require runtime usage; cache/peak memory/physical NPU/thermal state not measured. No automatic model download, retry or crash loop.'};}
async function unload(){if(!engine)return;const old=engine;engine=null;loaded=null;mark('engine-exit-before-await');try{await old.exit();mark('engine-exit-completed');}catch(e){mark('engine-exit-error',{error:failText(e)});}controls();}
$('load').onclick=async()=>{if(busy)return;let config;try{config=validateChoice({model:$('model').value,offload:$('offload').value,context:$('context').value,files:$('files').files});}catch(e){status(failText(e));return;}
busy=true;controls();try{await unload();report=newReport(config);mark('load-start',{model:config.model,offload:config.offload,context:config.context});status('Importing independent wllama runtime…');
mark('runtime-import-before-await');const mod=await import(RUNTIME_URL);WllamaClass=mod.Wllama;if(typeof WllamaClass!=='function')throw Error('Runtime did not export Wllama constructor');mark('runtime-import-completed');
engine=new WllamaClass({default:WASM_URL});engine.setCompat('default');const opt={n_gpu_layers:config.offload,n_ctx:config.context,n_threads:1,progressCallback:({loaded,total})=>{if(total&&loaded)status(`Downloading or reading model: ${Math.round(100*loaded/total)}% (library progress)`);}};
mark('model-load-before-await');const start=clock();if(config.model==='local')await engine.loadModel(Array.from($('files').files),opt);else await engine.loadModelFromUrl(MODELS[config.model].url,opt);const loadMs=clock()-start;
loaded=config;report.load={wallMs:loadMs,cacheState:'unknown',estimatedDownloadMB:config.remoteDownloadEstimateMB};report.phase='ready';mark('model-ready',{wallMs:Math.round(loadMs)});status('Model ready. Run one-token inference first.');
}catch(e){const msg=failText(e);if(report){report.errors.push({stage:report.stage,error:msg});report.phase='failed';report.finishedAt=time();mark('load-failed',{error:msg});}status('Model load failed: '+msg);if(engine)await unload();}finally{busy=false;controls();}};
async function infer(tokens,stream){if(busy||!engine||!loaded)return;busy=true;controls();report.phase='inference';report.finishedAt=null;mark('request-before-await',{tokens,stream});status(`Running ${tokens}-token ${stream?'streaming':'nonstreaming'} request…`);
const start=clock();let firstText=null,output='',chunks=0,usage=null;const req={messages:[{role:'user',content:'Write a short list of common English nouns separated by spaces. Answer directly.'}],max_tokens:tokens,temperature:0,stream};
try{if(stream){const iterator=await engine.createChatCompletion(req);mark('stream-created');for await(const chunk of iterator){chunks++;const text=chunk.choices?.[0]?.delta?.content??'';if(text){if(firstText===null){firstText=clock();mark('first-text',{elapsedMs:Math.round(firstText-start)});}output+=text;}if(chunk.usage)usage=chunk.usage;}}
else{const result=await engine.createChatCompletion(req);mark('response-received');output=result.choices?.[0]?.message?.content??'';usage=result.usage??null;if(output)firstText=clock();}
const metric=resultMetrics({start,firstText,end:clock(),usage,output,chunks,mode:stream?'stream':'nonstream'});report.results.push({status:'completed',tokensRequested:tokens,metrics:metric});report.phase='completed';report.finishedAt=time();mark('inference-completed',{tokens,wallMs:Math.round(metric.wallMs),completionTokens:metric.completionTokens});$('output').textContent=output||'(Empty model output)';status(`Completed. ${metric.completionTokens??'unknown'} reported output tokens, ${Math.round(metric.wallMs)} ms; export JSON.`);
}catch(e){const msg=failText(e);report.errors.push({stage:'inference',tokens,stream,error:msg});report.phase='failed';report.finishedAt=time();mark('inference-failed',{error:msg});status('Inference error: '+msg);}
finally{busy=false;controls();}}
$('one').onclick=()=>infer(1,false);$('sixtyfour').onclick=()=>infer(64,true);$('release').onclick=async()=>{if(busy)return;busy=true;controls();report.phase='unloading';mark('unload-requested');try{await unload();report.phase='released';report.finishedAt=time();mark('released');status('Model unloaded. Select the next configuration.');}finally{busy=false;controls();}};
const json=()=>JSON.stringify(report??{app:'PocketBench independent GGUF inference',status:'no report'},null,2);
function filename(){return `pocketbench-wllama-${time().replace(/[:.]/g,'-')}.json`;}
function download(){const url=URL.createObjectURL(new Blob([json()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename();a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('save').onclick=download;$('share').onclick=async()=>{const f=new File([json()],filename(),{type:'application/json'});try{if(navigator.canShare?.({files:[f]}))await navigator.share({files:[f],title:'PocketBench independent inference'});else download();}catch(e){if(e.name!=='AbortError')status('Share unavailable: '+failText(e)+'; use Save JSON.');}};
window.addEventListener('error',e=>{if(report){report.errors.push({stage:'window-error',error:e.message});mark('window-error',{error:e.message});}});window.addEventListener('unhandledrejection',e=>{if(report){const msg=failText(e.reason);report.errors.push({stage:'unhandled-rejection',error:msg});mark('unhandled-rejection',{error:msg});}});
const previous=(()=>{try{const s=localStorage.getItem(STORAGE_KEY);return s?JSON.parse(s):null;}catch{return null;}})();if(previous){report=previous;render();$('previous').textContent=incomplete(previous)?`Prior run ended without a completion checkpoint: ${previous.phase} / ${previous.stage}. Export before another load.`:`Saved report: ${previous.phase}, ${previous.results?.length||0} requests. Export before overwriting.`;}
$('capabilities').textContent=`WebGPU: ${navigator.gpu?'exposed':'unavailable'} · Wasm: ${typeof WebAssembly!=='undefined'?'yes':'no'} · cross-origin isolated: ${globalThis.crossOriginIsolated??'unknown'} · hardwareConcurrency hint: ${navigator.hardwareConcurrency??'unknown'}.`;
