import assert from 'node:assert/strict';
import {CANDIDATES,PROMPTS,percentiles,normalizeUsage,finishMeasurement,summary,modelCatalog,LIBRARY_VERSION} from '../ai-bench-metrics.mjs';
assert.equal(LIBRARY_VERSION,'0.2.85');
assert(PROMPTS.long.length>PROMPTS.medium.length&&PROMPTS.medium.length>PROMPTS.short.length);
assert.equal(percentiles([]),null);
assert.deepEqual(percentiles([4,1,3,2]),{n:4,median:2.5,p10:1.3,p90:3.7,p95:3.8499999999999996,min:1,max:4});
const u={prompt_tokens:32,completion_tokens:21,extra:{prefill_tokens_per_s:120,decode_tokens_per_s:30,ttft_s:0.4}};
assert.equal(normalizeUsage(u).modelDecodeTokensPerSecond,30);
const got=finishMeasurement({start:100,firstVisible:500,end:1500,chunkCount:8,usage:u,text:'demo'});
assert.equal(got.timeToFirstVisibleTextMs,400);assert.equal(got.approximateDecodeTokensPerSecond,20);assert.equal(got.endToEndTokensPerSecond,15);
assert.equal(finishMeasurement({start:0,firstVisible:null,end:1000,chunkCount:0,usage:null,text:''}).approximateDecodeTokensPerSecond,null);
assert.equal(finishMeasurement({start:0,firstVisible:0,end:10,chunkCount:10,usage:null,text:'a'}).usage.completionTokens,null);
const s=summary([{status:'completed',metrics:got},{status:'failed',metrics:null}]);assert.equal(s.completed,1);assert.equal(s.failed,1);assert.equal(s.medianDecodeTokensPerSecond.median,30);
const m=modelCatalog([{model_id:CANDIDATES[1].id,vram_required_MB:900,required_features:['shader-f16']}]);assert.equal(m[1].available,true);assert.equal(m[0].available,false);assert.equal(m[1].estimatedRuntimeMemoryMB,900);
console.log('PASS: 12 model/metric/empty-result/catalog/suite assertions');
