import assert from 'node:assert/strict';
import {captureLocations,examineCapture,makeFrameCapture,RECORD_BYTES,ROW_BYTES} from '../frame-observer.js';
import {runBatched} from '../suite-observed-worker.js';
assert.equal(RECORD_BYTES,2048);
assert.equal(captureLocations(768,390).length,2);
const bytes=new Uint8Array(RECORD_BYTES*3);
const fill=(n,extra)=>{for(let p=0;p<2;p++)for(let y=0;y<4;y++)for(let x=0;x<16;x++){
 const at=n*RECORD_BYTES+p*1024+y*ROW_BYTES+x*4;
 bytes.set([12,5,3,255],at);
 if(extra&&p===0&&y===1&&x===1)bytes.set([12,5,30+n,255],at);
}};
fill(0,false);fill(1,true);fill(2,true);
const obs=examineCapture(bytes,3,'bgra8unorm',[[1,1],[2,2]]);
assert.equal(obs.capturedFrames,3);assert.equal(obs.framesWithNonBackground,2);
assert.equal(obs.nonBackgroundPixels,2);assert.equal(obs.changedAdjacentSamples,2);
assert.equal(obs.uniqueSampleHashes,3);assert.equal(obs.sampleLocations.length,2);
assert.throws(()=>examineCapture(bytes,4),/mismatch/);
const oldUsage=globalThis.GPUBufferUsage,oldMap=globalThis.GPUMapMode;
globalThis.GPUBufferUsage={COPY_DST:8,MAP_READ:1};globalThis.GPUMapMode={READ:1};
let bufferAlloc,commands=[];const fakeGPU={limits:{maxBufferSize:99999999},createBuffer(o){bufferAlloc=o;return {async mapAsync(){},getMappedRange(){return bytes;},unmap(){},destroy(){}};}};
const texture={};const cap=makeFrameCapture(fakeGPU,texture,768,390,500,'bgra8unorm');
const encoder={copyTextureToBuffer(...args){commands.push(args);}};
cap.capture(encoder,texture);cap.capture(encoder,texture);
assert.equal(cap.frames,2);assert.equal(commands.length,4);
assert.deepEqual(commands.map(c=>c[1].offset),[0,1024,2048,3072]);
assert.equal(commands.every(c=>c[1].bytesPerRow===256&&c[1].rowsPerImage===4),true);
assert.equal(bufferAlloc.usage,9);assert.throws(()=>cap.capture(encoder,{}),/mismatch/);
cap.destroy();globalThis.GPUBufferUsage=oldUsage;globalThis.GPUMapMode=oldMap;
let t=0,queued=0,done=0;
const batch=await runBatched({submit(){queued++;t+=.5},async drain(){done=queued;t+=2},now:()=>t,stop:()=>false,batch:4,durationMs:110});
assert.equal(batch.completedFrames,queued);assert.equal(batch.completedFrames,done);
assert.ok(batch.completedFramesPerSecond>0);
const {ObservedLab}=await import('../observed-engine.js');
let order=[];const observed=Object.create(ObservedLab.prototype);
observed.render=true;observed.running=true;observed.paused=false;observed.bench=null;
observed.raf=()=>{};observed.previousFrameAt=null;observed.frameNumber=0;
observed.time=0;observed.steps=2;observed.count=65536;observed.sampleEvery=Number.MAX_SAFE_INTEGER;
observed.hasTimestamp=false;observed.queryPending=false;observed.mode='fused';observed.fusedAvailable=true;
observed.updateUniform=()=>order.push('uniform');observed.computeBindGroup={};observed.renderBindGroup={};
observed.fusedPipeline={};observed.baselinePipeline={};observed.graphics={};observed.fpsFrames=0;
observed.fpsStart=performance.now();observed.emit=()=>{};
const tex={createView(){return {}}};observed.context={getCurrentTexture(){return tex;}};
observed.frameCapture={capture(e,t){assert.equal(t,tex);order.push('capture');}};
observed.device={createCommandEncoder(){return {
 beginComputePass(){return {setPipeline(){},setBindGroup(){},dispatchWorkgroups(){order.push('compute');},end(){order.push('compute-end');}};},
 beginRenderPass(){return {setPipeline(){},setBindGroup(){},draw(){order.push('render');},end(){order.push('render-end');}};},
 finish(){return {}},};},queue:{submit(){order.push('submit');}}};
observed.onFrame(performance.now());
assert.deepEqual(order,['uniform','compute','compute-end','render','render-end','capture','submit']);
assert.equal(observed.frameNumber,1);
assert.equal(observed.time,2/120);
console.log('PASS observed capture: offsets, pixel changes, queue accounting and render order');
