import {VERSION,RUNTIME_VERSION,RUNTIME_URL,MODELS,defaultRequest,normalizeRequest,appendUser,addAssistant,usageMetrics,asJSON} from './chat-core.mjs?v=0.1.0';
const $=id=>document.getElementById(id), time=()=>performance.now(), stamp=()=>new Date().toISOString();
const STORAGE='pocketbench-chat-session-v1';
let runtime=null,engine=null,worker=null,loaded=null,busy=false,seq=0,active=null,turns=[],runs=[],events=[],lastRaw=null,lastAnswer='',request=defaultRequest(),firstLoad=null;
function event(stage,details={}){events.push({at:stamp(),stage,...details});if(events.length>100)events.shift();$('log').textContent=events.slice(-35).map(x=>`${x.at.slice(11,19)} ${x.stage}${x.message?' — '+x.message:''}`).join('\n');persist();}
function status(s){$('status').textContent=s;}
function persist(){try{sessionStorage.setItem(STORAGE,JSON.stringify({version:VERSION,model:$('model').value,request,turns:turns.slice(-40),runs:runs.slice(-30),events:events.slice(-50),lastAnswer,lastRaw:lastRaw?JSON.stringify(lastRaw).slice(0,20000):null}));}catch(e){$('outputNotice').textContent='Session storage unavailable; export JSON to retain results.';}}
function controls(){const ready=!!engine&&!!loaded&&!busy&&$('model').value===loaded;const loading=active?.kind==='load';$('load').disabled=!runtime||busy;$('model').disabled=busy;$('unload').disabled=!engine||busy;$('send').disabled=!ready;$('stop').disabled=!active;$('copy').disabled=!lastAnswer;$('apply').disabled=busy;$('sync').disabled=busy;$('runJson').disabled=!ready;}
function renderChat(){const el=$('chat');el.replaceChildren();const visible=turns.filter(m=>m.role==='user'||m.role==='assistant');if(!visible.length){const hint=document.createElement('p');hint.className='help';hint.textContent='No messages yet. Load a model, write a prompt, or compose an exact request in the JSON tab.';el.append(hint);}for(const m of visible){const article=document.createElement('article');article.className='msg '+m.role;const meta=document.createElement('div');meta.className='meta';meta.textContent=m.role==='user'?'You':`Assistant${m.model?' · '+m.model.replace(/-q.*$/,''):''}${m.interrupted?' · interrupted':''}`;const body=document.createElement('div');body.className='body';body.textContent=m.content;article.append(meta,body);if(m.stats){const s=document.createElement('div');s.className='stats';s.textContent=m.stats;article.append(s);}el.append(article);}el.scrollTop=el.scrollHeight;}
function toEditor(){ $('request').value=asJSON(request);$('requestError').textContent='';}
function fromEditor(){let parsed;try{parsed=JSON.parse($('request').value);parsed=normalizeRequest(parsed,loaded??$('model').value);}catch(e){$('requestError').textContent=e.message;throw e;}request=parsed;turns=parsed.messages.map(m=>({role:m.role,content:m.content}));toEditor();renderChat();persist();event('request-applied',{message:`${turns.length} messages`});return parsed;}
function setTab(which){for(const name of ['chat','json','results']){$('view-'+name).hidden=name!==which;$('tab-'+name).setAttribute('aria-selected',String(name===which));}if(which==='results')$('result').textContent=asJSON(lastRaw??{status:'no-completion-yet',runs});}
for(const name of ['chat','json','results'])$('tab-'+name).onclick=()=>setTab(name);
function resetEngine(){try{engine?.interruptGenerate?.();}catch{}try{worker?.terminate();}catch{}engine=null;worker=null;loaded=null;}
function cancel(){if(!active)return;const old=active;seq++;active=null;busy=false;try{engine?.interruptGenerate?.();}catch{}if(old.kind==='load'){resetEngine();status('Model load cancelled. Existing browser model cache is retained.');}else{status('Interrupt requested; generation may return partial text.');}event('cancelled',{message:old.kind});controls();}
$('stop').onclick=cancel;
$('model').addEventListener('change',()=>{const item=MODELS.find(m=>m.id===$('model').value);$('modelInfo').textContent=`${item.label}. Catalog estimate ${item.estimateMB.toLocaleString()} MB; not measured Safari allocation. ${item.tier==='stretch'?'High risk of tab termination: large weights plus KV cache and scratch allocations.':'Test actual loading and sustained decoding.'}`;if(loaded&&item.id!==loaded)status(`Loaded model is ${loaded}. Unload or Load to switch to ${item.id}.`);request.model=item.id;toEditor();controls();});
$('load').onclick=async()=>{if(!runtime||busy)return;const id=$('model').value,item=MODELS.find(m=>m.id===id);if(!item)return;if(item.tier==='stretch'&&!confirm('The 8B model has a catalog estimate of ~5.7 GB GPU memory, plus browser/runtime overhead. It may terminate this tab and download gigabytes of weights. Try loading it?'))return;
 const job=++seq;busy=true;active={kind:'load',job};resetEngine();controls();event('load-start',{model:id,estimateMB:item.estimateMB});status(`Loading ${item.label}…`);$('progress').textContent='Model weights download only after this tap. This may use cached files.';const started=time();try{
  worker=new Worker('./ai-bench-worker.mjs',{type:'module'});
  worker.addEventListener('error',e=>{if(job===seq){event('worker-error',{message:e.message||'unknown worker error'});status('Worker error. Export session or Cancel load.');}});
  worker.addEventListener('messageerror',()=>{if(job===seq)event('worker-messageerror');});
  engine=await runtime.CreateWebWorkerMLCEngine(worker,id,{initProgressCallback:p=>{if(job!==seq)return;const text=String(p?.text||'');if(text){$('progress').textContent=text.slice(0,260);if(/finish|error|compile|shader/i.test(text))event('load-progress',{message:text.slice(0,180)});}}});
  if(job!==seq){try{await engine?.unload?.();}catch{}return;}
  loaded=id;active=null;busy=false;firstLoad=time()-started;status(`Model ready: ${id}. Send a message or run the JSON request.`);event('model-ready',{model:id,loadWallMs:Math.round(firstLoad)});request.model=id;toEditor();
 }catch(e){if(job!==seq)return;const message=String(e?.stack||e);event('load-failed',{message:message.slice(0,800)});status(`Load failed: ${e?.message||e}`);resetEngine();active=null;busy=false;}finally{if(job===seq)controls();}};
$('unload').onclick=async()=>{if(busy)return;seq++;active=null;busy=true;const old=engine;engine=null;loaded=null;controls();try{if(old)await Promise.race([old.unload(),new Promise(r=>setTimeout(r,1800))]);}catch(e){event('unload-error',{message:String(e)});}resetEngine();busy=false;status('Model unloaded; downloaded weights remain in browser cache.');event('unloaded');controls();};
function isUserTurn(r){return r.messages.some(m=>m.role==='user'&&m.content.trim());}
async function generate({composer=false}={}){if(!engine||!loaded||busy){status('Load a model before sending.');return;}let input;try{input=fromEditor();if(composer){input=appendUser(input,$('compose').value);if(!$('compose').value.trim()&&!isUserTurn(input))throw Error('Type a message or put a user message in the JSON.');}if(!isUserTurn(input))throw Error('The request needs at least one nonempty user message.');input=normalizeRequest(input,loaded);}catch(e){setTab('json');status('Fix the request JSON before generating.');$('requestError').textContent=e.message;return;}
 const job=++seq;busy=true;active={kind:'generate',job};controls();request=input;turns=input.messages.map(m=>({role:m.role,content:m.content}));toEditor();$('compose').value='';renderChat();const reply={role:'assistant',content:'',model:loaded};turns.push(reply);renderChat();event('request-before-await',{model:loaded,messages:input.messages.length,maxTokens:input.max_tokens,stream:input.stream});const start=time();let first=null,usage=null,raw=[],chunks=0,finishReason=null,reasoning='';status('Generating locally…');try{
 if(input.stream!==false){const stream=await engine.chat.completions.create(input);for await(const chunk of stream){if(job!==seq)return;raw.push(chunk);const delta=chunk.choices?.[0]?.delta??{};const text=delta.content??'';if(typeof text==='string'&&text){if(first===null)first=time();reply.content+=text;chunks++;renderChat();}if(typeof delta.reasoning_content==='string')reasoning+=delta.reasoning_content;if(chunk.usage)usage=chunk.usage;if(chunk.choices?.[0]?.finish_reason)finishReason=chunk.choices[0].finish_reason;}}
 else{const response=await engine.chat.completions.create(input);if(job!==seq)return;raw=[response];reply.content=response.choices?.[0]?.message?.content??'';reasoning=response.choices?.[0]?.message?.reasoning_content??'';first=reply.content?time():null;usage=response.usage??null;finishReason=response.choices?.[0]?.finish_reason??null;}
 if(job!==seq)return;const metrics=usageMetrics(usage,start,first,time());reply.stats=`${metrics.wallMs.toFixed(0)} ms · ${metrics.modelDecodeTokensPerSecond?.toFixed(1)??'—'} model tok/s · ${metrics.completionTokens??'—'} tokens`;lastAnswer=reply.content;lastRaw={request:input,output:reply.content,reasoning,usage,finishReason,chunks,rawResponse:raw,metrics};runs.push({at:stamp(),model:loaded,request:input,response:reply.content,reasoning,metrics,finishReason,chunks});if(runs.length>40)runs.shift();request=addAssistant(input,reply.content);toEditor();renderChat();$('metrics').textContent=reply.stats;status(`Completed. ${metrics.modelDecodeTokensPerSecond?.toFixed(2)??'No reported'} decode tokens/s; response is shown and exportable.`);event('generation-completed',{model:loaded,wallMs:Math.round(metrics.wallMs),completionTokens:metrics.completionTokens});$('result').textContent=asJSON(lastRaw);
 }catch(e){if(job!==seq)return;const message=String(e?.stack||e);lastRaw={request:input,partialOutput:reply.content,error:message,rawResponse:raw};status(`Inference error: ${e?.message??e}. Export the report.`);event('inference-failed',{message:message.slice(0,600)});$('result').textContent=asJSON(lastRaw);renderChat();}finally{if(job===seq){busy=false;active=null;controls();persist();}}}
$('send').onclick=()=>generate({composer:true});
$('compose').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!$('send').disabled)$('send').click();}});
$('apply').onclick=()=>{try{fromEditor();status('Edited JSON applied. Use Run JSON to send the exact request.');}catch{status('Invalid JSON; see error below editor.');}};
const runJson=document.createElement('button');runJson.id='runJson';runJson.className='primary';runJson.textContent='Run JSON';$('apply').insertAdjacentElement('afterend',runJson);runJson.onclick=()=>generate({composer:false});
$('sync').onclick=()=>{request={...defaultRequest(loaded??$('model').value),messages:turns.map(m=>({role:m.role,content:m.content}))};toEditor();status('JSON rebuilt from displayed messages. Previous custom request fields were reset.');event('request-rebuilt');};
$('copyRequest').onclick=()=>{navigator.clipboard?.writeText($('request').value).then(()=>status('Request JSON copied.')).catch(()=>status('Clipboard unavailable; select and copy JSON manually.'));};
$('copy').onclick=()=>{navigator.clipboard?.writeText(lastAnswer).then(()=>status('Answer copied.')).catch(()=>status('Clipboard unavailable; select and copy the answer manually.'));};
$('new').onclick=()=>{if(busy){status('Stop or finish the active operation before starting another conversation.');return;}request=defaultRequest(loaded??$('model').value);turns=[];lastAnswer='';lastRaw=null;toEditor();renderChat();$('metrics').textContent='';$('result').textContent='No inference yet.';event('new-conversation');status('New conversation. Model remains loaded.');controls();};
$('export').onclick=()=>{const report={app:'PocketBench local chat',version:VERSION,runtime:RUNTIME_VERSION,exportedAt:stamp(),device:{userAgent:navigator.userAgent,webgpu:!!navigator.gpu,crossOriginIsolated:crossOriginIsolated},selectedModel:$('model').value,loadedModel:loaded,modelLoadMs:firstLoad,requestEditor:$('request').value,request,turns,runs,events,lastRaw};const blob=new Blob([asJSON(report)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`pocketbench-chat-${stamp().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);status('Session JSON export requested.');};
try{const saved=JSON.parse(sessionStorage.getItem(STORAGE)||'null');if(saved?.version===VERSION){if(MODELS.some(m=>m.id===saved.model))$('model').value=saved.model;request=normalizeRequest(saved.request??defaultRequest($('model').value),$('model').value);turns=Array.isArray(saved.turns)?saved.turns.slice(-40):[];runs=Array.isArray(saved.runs)?saved.runs.slice(-30):[];events=Array.isArray(saved.events)?saved.events.slice(-50):[];lastAnswer=saved.lastAnswer??'';lastRaw=saved.lastRaw?JSON.parse(saved.lastRaw):null;$('progress').textContent='Session restored, but GPU model must be loaded again.';renderChat();}}catch(e){$('progress').textContent='Saved session could not be restored; starting clean.';request=defaultRequest();turns=[];}
toEditor();renderChat();controls();$('model').dispatchEvent(new Event('change'));
(async()=>{try{if(!navigator.gpu)throw Error('This browser does not expose WebGPU.');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('No WebGPU adapter available.');runtime=await import(RUNTIME_URL);const catalog=runtime.prebuiltAppConfig?.model_list??[];const features=adapter.features;for(const m of MODELS){const option=[...$('model').options].find(o=>o.value===m.id),entry=catalog.find(x=>x.model_id===m.id);if(!entry){option.disabled=true;option.textContent+=' · missing in pinned catalog';}else if((entry.required_features??[]).some(f=>!features.has(f))){option.disabled=true;option.textContent+=' · GPU feature missing';}else option.textContent+=` · ~${Math.round(entry.vram_required_MB??m.estimateMB)} MB estimated`;}status(`Runtime ${RUNTIME_VERSION} ready · Apple/WebGPU adapter: ${adapter.info?.vendor??'undisclosed'}. Select and load a model.`);event('runtime-ready',{modelCount:catalog.length,adapterVendor:adapter.info?.vendor??null});if($('model').selectedOptions[0]?.disabled){const first=[...$('model').options].find(o=>!o.disabled);if(first)$('model').value=first.value;request.model=$('model').value;toEditor();}controls();}catch(e){status(`Runtime unavailable: ${e?.message||e}`);event('runtime-failed',{message:String(e)});}})();
