import {VERSION,RUNTIME_VERSION,RUNTIME_URL,MODELS,defaultRequest,normalizeRequest,appendUser,addAssistant,usageMetrics,asJSON} from './chat-core.mjs?v=0.1.1';
const $=id=>document.getElementById(id),time=()=>performance.now(),stamp=()=>new Date().toISOString(),STORE='pocketbench-chat-session-v2';
let runtime=null,engine=null,worker=null,loaded=null,busy=false,seq=0,active=null,turns=[],runs=[],events=[],lastRaw=null,lastAnswer='',request=defaultRequest(),firstLoad=null;
function status(s){$('status').textContent=s;}
function persist(){try{const compact=lastRaw?{request:lastRaw.request,output:lastRaw.output,partialOutput:lastRaw.partialOutput,reasoning:lastRaw.reasoning,usage:lastRaw.usage,finishReason:lastRaw.finishReason,metrics:lastRaw.metrics,error:lastRaw.error}:null;sessionStorage.setItem(STORE,JSON.stringify({version:VERSION,model:$('model').value,request,turns:turns.slice(-40),runs:runs.slice(-25),events:events.slice(-50),lastAnswer,lastRaw:compact}));}catch{$('outputNotice').textContent='Session checkpoint unavailable or full. Export your JSON to retain results.';}}
function event(stage,details={}){events.push({at:stamp(),stage,...details});if(events.length>100)events.shift();$('log').textContent=events.slice(-35).map(x=>`${x.at.slice(11,19)} ${x.stage}${x.message?' — '+x.message:''}`).join('\n');persist();}
function controls(){const ready=!!engine&&!!loaded&&!busy&&$('model').value===loaded;$('load').disabled=!runtime||busy;$('model').disabled=busy;$('unload').disabled=!engine||busy;$('send').disabled=!ready;$('stop').disabled=!active;$('copy').disabled=!lastAnswer;$('apply').disabled=busy;$('sync').disabled=busy;$('runJson').disabled=!ready;}
function renderChat(){const el=$('chat');el.replaceChildren();const visible=turns.filter(m=>m.role==='user'||m.role==='assistant');if(!visible.length){const p=document.createElement('p');p.className='help';p.textContent='No messages yet. Load a model, write a prompt, or run an exact request from the JSON tab.';el.append(p);}for(const m of visible){const article=document.createElement('article');article.className='msg '+m.role;const meta=document.createElement('div');meta.className='meta';meta.textContent=m.role==='user'?'You':`Assistant${m.model?' · '+m.model.replace(/-q.*$/,''):''}${m.interrupted?' · interrupted':''}`;const body=document.createElement('div');body.className='body';body.textContent=m.content;article.append(meta,body);if(m.stats){const s=document.createElement('div');s.className='stats';s.textContent=m.stats;article.append(s);}el.append(article);}el.scrollTop=el.scrollHeight;}
function toEditor(){$('request').value=asJSON(request);$('requestError').textContent='';}
function fromEditor(){let parsed;try{parsed=normalizeRequest(JSON.parse($('request').value),loaded??$('model').value);}catch(e){$('requestError').textContent=e.message;throw e;}request=parsed;turns=parsed.messages.map(m=>({role:m.role,content:m.content}));toEditor();renderChat();event('request-applied',{message:`${turns.length} messages`});return parsed;}
function setTab(selected){for(const name of ['chat','json','results']){$('view-'+name).hidden=name!==selected;$('tab-'+name).setAttribute('aria-selected',String(name===selected));}if(selected==='results')$('result').textContent=asJSON(lastRaw??{status:'no-completion-yet',runs});}
for(const name of ['chat','json','results'])$('tab-'+name).onclick=()=>setTab(name);
function resetEngine(){try{engine?.interruptGenerate?.();}catch{}try{worker?.terminate();}catch{}engine=null;worker=null;loaded=null;}
function cancel(){if(!active)return;const job=active;if(job.kind==='generate'&&!job.interruptRequested){job.interruptRequested=true;try{engine?.interruptGenerate?.();}catch{}$('stop').textContent='Force terminate worker';status('Interrupt requested. If generation does not finish, tap Force terminate.');event('interrupt-requested');return;}seq++;active=null;busy=false;resetEngine();$('stop').textContent='Stop generation';status(job.kind==='load'?'Load cancelled. Cached model weights are retained.':'Worker terminated to prevent overlapping requests. Reload the model.');event('operation-cancelled',{message:job.kind});controls();}
$('stop').onclick=cancel;
$('model').addEventListener('change',()=>{const item=MODELS.find(m=>m.id===$('model').value);if(!item)return;$('modelInfo').textContent=`${item.label}. Catalog estimate ${item.estimateMB.toLocaleString()} MB, NOT measured available browser memory. ${item.tier==='stretch'?'Large weights, scratch and KV allocations may terminate a mobile tab.':'Test real load and multi-turn throughput.'}`;if(loaded&&loaded!==item.id)status(`Loaded: ${loaded}. Press Load to switch models.`);request.model=item.id;toEditor();controls();});
$('load').onclick=async()=>{if(!runtime||busy)return;const id=$('model').value,item=MODELS.find(m=>m.id===id);if(!item||$('model').selectedOptions[0]?.disabled)return;if(item.tier==='stretch'&&!confirm('8B is listed in WebLLM but untested on your phone. Its GPU-memory estimate is about 5.7 GB plus browser overhead. Download and attempt loading?'))return;
 const job=++seq;busy=true;active={kind:'load',job};resetEngine();controls();event('load-start',{model:id,estimateMB:item.estimateMB});status(`Loading ${item.label}…`);$('progress').textContent='Weights may come from this browser’s cache; no inference server is used.';const start=time();let candidate=null;let thisWorker=null;try{
  thisWorker=new Worker('./ai-bench-worker.mjs',{type:'module'});worker=thisWorker;
  thisWorker.addEventListener('error',e=>{if(job===seq){event('worker-error',{message:e.message||'unknown worker error'});status('Worker error. Export session or Cancel load.');}});
  thisWorker.addEventListener('messageerror',()=>{if(job===seq)event('worker-messageerror');});
  candidate=await runtime.CreateWebWorkerMLCEngine(thisWorker,id,{initProgressCallback:p=>{if(job!==seq)return;const text=String(p?.text||'');if(text){$('progress').textContent=text.slice(0,260);if(/finish|error|compile|shader/i.test(text))event('load-progress',{message:text.slice(0,180)});}}});
  if(job!==seq){try{thisWorker.terminate();}catch{}return;}engine=candidate;loaded=id;active=null;busy=false;firstLoad=time()-start;status(`Model ready: ${id}. Send a message or run JSON.`);event('model-ready',{model:id,loadWallMs:Math.round(firstLoad)});request.model=id;toEditor();
 }catch(e){if(job!==seq)return;const msg=String(e?.stack||e);event('load-failed',{message:msg.slice(0,800)});status(`Load failed: ${e?.message||e}`);resetEngine();active=null;busy=false;}finally{if(job===seq)controls();}};
$('unload').onclick=async()=>{if(busy)return;seq++;active=null;busy=true;const old=engine;engine=null;loaded=null;controls();try{if(old)await Promise.race([old.unload(),new Promise(resolve=>setTimeout(resolve,1800))]);}catch(e){event('unload-error',{message:String(e)});}resetEngine();busy=false;status('Model unloaded; browser weight cache remains.');event('unloaded');controls();};
function isUserTurn(r){return r.messages.some(m=>m.role==='user'&&m.content.trim());}
async function generate({composer=false}={}){if(!engine||!loaded||busy){status('Load a model before sending.');return;}let input;try{input=fromEditor();if(composer){const message=$('compose').value.trim();if(!message)throw Error('Type a message, or use Run JSON to submit an existing user turn.');input=appendUser(input,message);}if(!isUserTurn(input))throw Error('Request needs a nonempty user message.');input=normalizeRequest(input,loaded);}catch(e){setTab('json');status('Fix the request before generating.');$('requestError').textContent=e.message;return;}
 const job=++seq;busy=true;active={kind:'generate',job,interruptRequested:false};controls();request=input;turns=input.messages.map(m=>({role:m.role,content:m.content}));toEditor();$('compose').value='';const reply={role:'assistant',content:'',model:loaded};turns.push(reply);renderChat();event('request-before-await',{model:loaded,messages:input.messages.length,maxTokens:input.max_tokens,stream:input.stream});const start=time();let first=null,usage=null,raw=[],chunks=0,finishReason=null,reasoning='';status('Generating locally…');try{
  if(input.stream!==false){const stream=await engine.chat.completions.create(input);for await(const chunk of stream){if(job!==seq)return;raw.push(chunk);const delta=chunk.choices?.[0]?.delta??{};const text=delta.content??'';if(typeof text==='string'&&text){if(first===null)first=time();reply.content+=text;chunks++;renderChat();}if(typeof delta.reasoning_content==='string')reasoning+=delta.reasoning_content;if(chunk.usage)usage=chunk.usage;if(chunk.choices?.[0]?.finish_reason)finishReason=chunk.choices[0].finish_reason;}}
  else{const response=await engine.chat.completions.create(input);if(job!==seq)return;raw=[response];reply.content=response.choices?.[0]?.message?.content??'';reasoning=response.choices?.[0]?.message?.reasoning_content??'';first=reply.content?time():null;usage=response.usage??null;finishReason=response.choices?.[0]?.finish_reason??null;}
  if(job!==seq)return;const interrupted=active?.interruptRequested??false;reply.interrupted=interrupted;const metrics=usageMetrics(usage,start,first,time());reply.stats=`${Math.round(metrics.wallMs)} ms · ${metrics.modelDecodeTokensPerSecond?.toFixed(1)??'—'} model tok/s · ${metrics.completionTokens??'—'} tokens`;lastAnswer=reply.content;lastRaw={request:input,output:reply.content,reasoning,usage,finishReason,chunks,rawResponse:raw,metrics,interrupted};runs.push({at:stamp(),model:loaded,request:input,response:reply.content,reasoning,metrics,finishReason,chunks,interrupted});if(runs.length>40)runs.shift();request=addAssistant(input,reply.content);toEditor();renderChat();$('metrics').textContent=reply.stats;status(`${interrupted?'Interrupted':'Completed'} · ${metrics.modelDecodeTokensPerSecond?.toFixed(2)??'No reported'} model decode tokens/s.`);event(interrupted?'generation-interrupted':'generation-completed',{model:loaded,wallMs:Math.round(metrics.wallMs),completionTokens:metrics.completionTokens});$('result').textContent=asJSON(lastRaw);
 }catch(e){if(job!==seq)return;const message=String(e?.stack||e);lastRaw={request:input,partialOutput:reply.content,error:message,rawResponse:raw};status(`Inference error: ${e?.message??e}. Export the report.`);event('inference-failed',{message:message.slice(0,600)});$('result').textContent=asJSON(lastRaw);renderChat();}finally{if(job===seq){busy=false;active=null;$('stop').textContent='Stop generation';controls();persist();}}}
$('send').onclick=()=>generate({composer:true});
$('compose').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!$('send').disabled)$('send').click();}});
$('apply').onclick=()=>{try{fromEditor();status('JSON applied. Run JSON sends exactly these messages.');}catch{status('Invalid request; see JSON editor error.');}};
const runJson=document.createElement('button');runJson.id='runJson';runJson.className='primary';runJson.textContent='Run JSON';$('apply').insertAdjacentElement('afterend',runJson);runJson.onclick=()=>generate({composer:false});
$('sync').onclick=()=>{request={...defaultRequest(loaded??$('model').value),messages:turns.map(m=>({role:m.role,content:m.content}))};toEditor();status('JSON rebuilt from messages; prior custom request fields reset.');event('request-rebuilt');};
function copy(text,label){if(!navigator.clipboard?.writeText){status('Clipboard API unavailable; select text to copy.');return;}navigator.clipboard.writeText(text).then(()=>status(`${label} copied.`)).catch(()=>status('Clipboard blocked; select and copy manually.'));}
$('copyRequest').onclick=()=>copy($('request').value,'Request JSON');$('copy').onclick=()=>copy(lastAnswer,'Answer');
$('new').onclick=()=>{if(busy){status('Finish or cancel the active operation first.');return;}request=defaultRequest(loaded??$('model').value);turns=[];lastAnswer='';lastRaw=null;toEditor();renderChat();$('metrics').textContent='';$('result').textContent='No inference yet.';event('new-conversation');status('New conversation; current model remains loaded.');controls();};
$('export').onclick=()=>{const report={app:'PocketBench local chat',version:VERSION,runtime:RUNTIME_VERSION,exportedAt:stamp(),device:{userAgent:navigator.userAgent,webgpu:!!navigator.gpu,crossOriginIsolated:crossOriginIsolated},selectedModel:$('model').value,loadedModel:loaded,modelLoadMs:firstLoad,requestEditor:$('request').value,request,turns,runs,events,lastRaw};const url=URL.createObjectURL(new Blob([asJSON(report)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`pocketbench-chat-${stamp().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);status('Session JSON export requested.');};
try{const saved=JSON.parse(sessionStorage.getItem(STORE)||'null');if(saved?.version===VERSION){if(MODELS.some(m=>m.id===saved.model))$('model').value=saved.model;request=normalizeRequest(saved.request??defaultRequest($('model').value),$('model').value);turns=Array.isArray(saved.turns)?saved.turns.slice(-40):[];runs=Array.isArray(saved.runs)?saved.runs.slice(-25):[];events=Array.isArray(saved.events)?saved.events.slice(-50):[];lastAnswer=saved.lastAnswer??'';lastRaw=saved.lastRaw??null;$('progress').textContent='Session restored; GPU model must be loaded again.';}}catch{$('progress').textContent='Saved session could not be restored; starting new.';request=defaultRequest();turns=[];}
toEditor();renderChat();controls();$('model').dispatchEvent(new Event('change'));
(async()=>{try{if(!navigator.gpu)throw Error('Browser does not expose WebGPU.');const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error('No WebGPU adapter available.');runtime=await import(RUNTIME_URL);const catalog=runtime.prebuiltAppConfig?.model_list??[],features=adapter.features;for(const m of MODELS){const option=[...$('model').options].find(o=>o.value===m.id),entry=catalog.find(x=>x.model_id===m.id);if(!entry){option.disabled=true;option.textContent+=' · unavailable in pinned catalog';}else if((entry.required_features??[]).some(f=>!features.has(f))){option.disabled=true;option.textContent+=' · required GPU feature missing';}else option.textContent+=` · ~${Math.round(entry.vram_required_MB??m.estimateMB)} MB estimated`;}status(`Runtime ${RUNTIME_VERSION} ready · adapter: ${adapter.info?.vendor??'undisclosed'}. Load a model.`);event('runtime-ready',{modelCount:catalog.length,adapterVendor:adapter.info?.vendor??null});if($('model').selectedOptions[0]?.disabled){const first=[...$('model').options].find(o=>!o.disabled);if(first)$('model').value=first.value;request.model=$('model').value;toEditor();}controls();}catch(e){status(`Runtime unavailable: ${e?.message||e}`);event('runtime-failed',{message:String(e)});}})();
